"""Assemble the results matrix: quality against cost, in seconds, per network profile.

Each benchmark writes its own JSONL. This is the one place that joins them and
converts counts into the unit the systems are actually comparable in -- how long a
query takes on a given link -- using the model in `netcost.py`.

Two conventions are applied consistently and are worth stating, because most
published comparisons quietly pick one or the other:

* **Dependent hops are charged serially, parallel fetches are not.** A frontier of
  sixteen pages costs about three round-trips at a browser's six-connection limit,
  not sixteen. Charging them serially would flatter narrow-beam configurations;
  charging them all in parallel would flatter wide ones.
* **Per-session fixed costs are amortised, not ignored.** An index that preloads a
  code blob is reported at several session lengths, because whether it wins is a
  property of the session rather than of the index.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools"))

from analyze.netcost import (  # noqa: E402
    CONCURRENCY_LEVELS,
    PAGE_BYTES,
    PROFILES,
    Access,
    query_seconds,
    session_seconds,
)

RESULTS = REPO / "bench" / "results"
PROFILE_ORDER = ["ideal", "wifi", "5g", "lte", "3g", "satellite"]

#: One representative configuration per system, chosen so the comparison is legible.
#: The full sweeps are in the JSONL files these are drawn from.
HEADLINE_CONFIGS = [
    ("fts5", "post-vacuum"),
    ("dense", "bfs/resident/L=128/beam=4/rerank=0/m=64"),
    ("dense", "bfs/resident/L=128/beam=4/rerank=100/m=32"),
    ("late", "k=1024/probe=8/rerank=0"),
    ("late", "k=1024/probe=8/rerank=100"),
]


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(l) for l in open(path) if l.strip()]


def fts5_pages(scale: str) -> dict | None:
    """FTS5 page access at `scale` in its deployment state.

    Post-vacuum is the state a served file would be in: section 9.1 measured that
    `optimize` alone leaves the file 27% larger than as-built, so the deployment
    recipe is optimize then VACUUM, and that is what should be compared against.
    """
    recs = load_jsonl(RESULTS / f"fts5-{scale}.jsonl")
    wanted = [r for r in recs
              if r.get("record") == "pages" and r.get("group") == "all"
              and r.get("phase") in ("post_vacuum", "post-vacuum")]
    if not wanted:
        wanted = [r for r in recs if r.get("record") == "pages" and r.get("group") == "all"]
    return wanted[-1] if wanted else None


def fmt_seconds(s: float) -> str:
    if s >= 100:
        return f"{s:,.0f} s"
    if s >= 1:
        return f"{s:.1f} s"
    return f"{s * 1000:.0f} ms"


def main() -> int:
    lines: list[str] = []
    w = lines.append

    w("# annlite results matrix\n")
    w("Generated by `tools/analyze/matrix.py`. Every count is measured; the seconds")
    w("are those counts put through the network model in `tools/analyze/netcost.py`,")
    w("which charges dependent hops serially and parallel fetches six at a time.\n")

    # --- network profiles --------------------------------------------------
    w("## Network profiles\n")
    w("| profile | RTT | throughput |")
    w("|---|---:|---:|")
    for name in PROFILE_ORDER:
        rtt, mbps = PROFILES[name]
        cap = "unlimited" if mbps == float("inf") else f"{mbps:g} Mbit/s"
        w(f"| `{name}` | {rtt:g} ms | {cap} |")
    w("")

    # --- FTS5 --------------------------------------------------------------
    w("## Baseline: FTS5\n")
    fts_any = False
    w("FTS5 discovers pages as it scores, so each distinct page is charged as its own")
    w("dependent fetch. That is the pessimistic bound; a client coalescing the")
    w("contiguous runs measured post-vacuum would do better, and that column is shown")
    w("alongside.\n")
    w("| scale | median pages/query | p95 | contiguous runs | KB read | " +
      " | ".join(f"`{p}`" for p in PROFILE_ORDER) + " |")
    w("|---|---:|---:|---:|---:|" + "---:|" * len(PROFILE_ORDER))
    for scale in ("100", "10k", "1m"):
        r = fts5_pages(scale)
        if not r:
            continue
        fts_any = True
        median = r["distinct_pages"]["median"]
        p95 = r["distinct_pages"]["p95"]
        runs = r.get("contiguous_runs", {}).get("median", median)
        kb = r.get("bytes_read", {}).get("median", median * PAGE_BYTES) / 1024
        cells = []
        for p in PROFILE_ORDER:
            acc = Access(hops=max(1, int(median)), requests=max(1, int(median)),
                         bytes_fetched=int(median * PAGE_BYTES))
            cells.append(fmt_seconds(query_seconds(acc, p)["total_s"]))
        w(f"| {scale} | {median:,.0f} | {p95:,.0f} | {runs:,.0f} | {kb:,.0f} | "
          + " | ".join(cells) + " |")
    if not fts_any:
        w("| _no FTS5 results found — run `make fts5`_ | | | | | " +
          " | ".join("" for _ in PROFILE_ORDER) + " |")
    w("")

    # --- dense ANN ---------------------------------------------------------
    w("## Dense ANN (Vamana + PQ)\n")
    for scale in ("10k", "100k", "1m"):
        recs = load_jsonl(RESULTS / f"ann-{scale}.jsonl")
        if not recs:
            continue
        meta = next((r for r in recs if r.get("record") == "meta"), {})
        idxs = {r["ordering"]: r for r in recs if r.get("record") == "index"}
        qs = [r for r in recs if r.get("record") == "query_set"]
        if not qs:
            continue
        w(f"### {meta.get('docs', scale):,} documents "
          f"(m={meta.get('m')} bytes/code, R={meta.get('r')}, alpha={meta.get('alpha')})\n")
        if idxs:
            first = next(iter(idxs.values()))
            w(f"Record {first.get('record_bytes')} bytes, "
              f"{first.get('records_per_page', 0):.1f} per 4 KiB page, "
              f"database {first.get('db_bytes', 0) / 1e6:,.1f} MB, "
              f"code blob {first.get('code_blob_bytes', 0) / 1e6:,.2f} MB.\n")
        w("| ordering | codes | L | beam | rerank | recall@10 | pages | runs | hops | " +
          " | ".join(f"`{p}`" for p in PROFILE_ORDER) + " |")
        w("|---|---|---:|---:|---:|---:|---:|---:|---:|" + "---:|" * len(PROFILE_ORDER))
        for r in sorted(qs, key=lambda x: (x["ordering"], x.get("mode", ""), x["l"],
                                           x.get("beam", 0), x["rerank"])):
            pages = r["mean_distinct_pages"]
            runs = r.get("mean_contiguous_runs", pages)
            hops = max(1, round(r["mean_hops"]))
            # Reranking fetches full float32 vectors for the candidate pool. Those
            # are scattered and 1.5 KB each, and they arrive in one extra dependent
            # round after the traversal finishes -- charging only the traversal would
            # make reranking look free, when section 7.3 showed it is the expensive
            # half of the query.
            rr_pages = r.get("mean_rerank_pages", 0)
            if rr_pages:
                hops += 1
                runs += rr_pages
                pages += rr_pages
            preload = 0
            if r.get("mode") == "resident":
                preload = meta.get("docs", 0) * meta.get("m", 0)
            # Coalesced runs are the request count a real client issues.
            acc = Access(hops=hops, requests=max(1, round(runs)),
                         bytes_fetched=int(pages * PAGE_BYTES), preload_bytes=preload)
            cells = [fmt_seconds(query_seconds(acc, p)["total_s"]) for p in PROFILE_ORDER]
            w(f"| {r['ordering']} | {r.get('mode','-')} | {r['l']} | {r.get('beam','-')} | "
              f"{r['rerank']} | {r['recall_at_10']:.3f} | {pages:,.0f} | {runs:,.0f} | "
              f"{hops} | " + " | ".join(cells) + " |")
        w("")

        # Resident codes carry a fixed preload, so report where they overtake.
        res = [r for r in qs if r.get("mode") == "resident"]
        dsk = [r for r in qs if r.get("mode") == "ondisk"]
        if res and dsk:
            w("#### Resident codes: session cost including the one-time preload\n")
            blob = meta.get("docs", 0) * meta.get("m", 0)
            w(f"Preload is {blob / 1e6:,.2f} MB. Chosen configuration: "
              f"L={res[0]['l']}, beam={res[0].get('beam')}, rerank={res[0]['rerank']}.\n")
            a = next((r for r in res if r["rerank"] == 0), res[0])
            b = next((r for r in dsk if r["l"] == a["l"] and r.get("beam") == a.get("beam")
                      and r["rerank"] == a["rerank"]), dsk[0])
            acc_r = Access(hops=max(1, round(a["mean_hops"])),
                           requests=max(1, round(a.get("mean_contiguous_runs", 1))),
                           bytes_fetched=int(a["mean_distinct_pages"] * PAGE_BYTES),
                           preload_bytes=blob)
            acc_d = Access(hops=max(1, round(b["mean_hops"])),
                           requests=max(1, round(b.get("mean_contiguous_runs", 1))),
                           bytes_fetched=int(b["mean_distinct_pages"] * PAGE_BYTES))
            w("Cheaper option in brackets. Per-query tables above exclude the preload;")
            w("this one includes it, which is the comparison that decides the design.\n")
            w("| profile | " + " | ".join(f"{n} quer{'y' if n == 1 else 'ies'}"
                                          for n in (1, 10, 100, 1000)) + " |")
            w("|---|" + "---:|" * 4)
            for p in PROFILE_ORDER:
                cells = []
                for n in (1, 10, 100, 1000):
                    sr = session_seconds(acc_r, p, n)
                    sd = session_seconds(acc_d, p, n)
                    if abs(sr - sd) < 1e-9:
                        # `ideal` has neither latency nor transfer cost, so the two
                        # are genuinely tied rather than one winning.
                        cells.append(f"{fmt_seconds(sr)} (tie)")
                    else:
                        better = "resident" if sr < sd else "on-disk"
                        cells.append(f"{fmt_seconds(min(sr, sd))} ({better})")
                w(f"| `{p}` | " + " | ".join(cells) + " |")
            w("")

    # --- retrieval quality -------------------------------------------------
    code = RESULTS / "code-eval.json"
    if code.exists():
        data = json.loads(code.read_text())
        w("## Retrieval quality on the code-search corpus\n")
        w(f"{data['documents']:,} functions, {data['queries']} docstring queries. "
          "Ground truth is the corpus construction, so no judgments are involved.\n")
        w("| system | success@1 | success@10 | success@100 | MRR@10 | bytes/doc | ms/query |")
        w("|---|---:|---:|---:|---:|---:|---:|")
        for name, m in data["results"].items():
            bpd = m.get("bytes_per_doc", "—")
            bpd = f"{bpd:,}" if isinstance(bpd, (int, float)) else bpd
            w(f"| {name} | {m['success@1']:.3f} | {m['success@10']:.3f} | "
              f"{m['success@100']:.3f} | {m['mrr@10']:.3f} | {bpd} | {m['ms_per_query']:.2f} |")
        w("")

    # --- three systems on one corpus ---------------------------------------
    tri = load_jsonl(RESULTS / "tri-code.jsonl") + load_jsonl(RESULTS / "tri-late.jsonl")
    if tri:
        w("## Three systems on one corpus\n")
        w("Code corpus, 3,366 documents, 500 queries. Same single-gold quality")
        w("definition for all three, and the same pass-through VFS counting real file")
        w("pages. `success@1` has a ceiling of 0.962: 7.4% of queries share a docstring")
        w("with another function and cannot be answered as known-item retrieval.\n")
        w("CPU is process time measured under contention — the ordering is meaningful,")
        w("the absolute values are an upper bound.\n")
        w("| system | configuration | success@1 | of max | MRR@10 | pages | requests | bytes/doc | cpu ms |")
        w("|---|---|---:|---:|---:|---:|---:|---:|---:|")
        for sysname, cfg in HEADLINE_CONFIGS:
            r = next((x for x in tri if x["system"] == sysname and x["config"] == cfg), None)
            if not r:
                continue
            q = r["quality"]
            w(f"| {sysname} | {cfg} | {q['success@1']:.3f} | {q['success@1'] / 0.962:.3f} | "
              f"{q['mrr@10']:.3f} | {r['pages']['mean']:,.1f} | {r['requests']['mean']:,.1f} | "
              f"{r['bytes_per_doc']:,.0f} | {r['cpu_ms_per_query']:.2f} |")
        w("")

        # --- what parallelism does ------------------------------------------
        w("### Requests in flight\n")
        w("Requests within a hop overlap, because their addresses are known together.")
        w("Hops do not, because the next hop's addresses are unknown until the current")
        w("returns. So parallelism divides the first and leaves the second, and latency")
        w("is bounded below by `hops x RTT` however wide the pipe.\n")
        w("FTS5 is marked unbatchable: `xRead` is synchronous, so SQLite asks for its")
        w("next page only after the current one returns. That is a property of the")
        w("client, not of the index.\n")
        try:
            from analyze.concurrency import rows_for_comparison
            access_rows = rows_for_comparison()
        except Exception as exc:  # measurement files incomplete
            access_rows = []
            w(f"_Concurrency table unavailable: {exc}_\n")
        for profile in ("lte", "3g", "satellite"):
            if not access_rows:
                break
            rtt, mbps = PROFILES[profile]
            w(f"**`{profile}`** ({rtt:g} ms RTT, {mbps:g} Mbit/s), seconds per query:\n")
            w("| system | hops | requests | " +
              " | ".join(f"c={c}" for c in CONCURRENCY_LEVELS) + " | floor |")
            w("|---|---:|---:|" + "---:|" * (len(CONCURRENCY_LEVELS) + 1))
            for label, acc in access_rows:
                cells = " | ".join(
                    fmt_seconds(query_seconds(acc, profile, c)["total_s"])
                    for c in CONCURRENCY_LEVELS
                )
                floor = fmt_seconds(query_seconds(acc, profile, 1)["floor_s"])
                w(f"| {label} | {acc.hops} | {acc.requests} | {cells} | **{floor}** |")
            w("")

    out = REPO / "docs" / "RESULTS.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"-> {out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
